# Generated by Django 2.2.7 on 2020-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100, verbose_name='Question Title')),
            ],
            options={
                'verbose_name': 'TextQuestion',
                'verbose_name_plural': 'TextQuestions',
            },
        ),
    ]
