# Generated by Django 2.2.7 on 2020-05-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200524_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100, verbose_name='Question Text')),
            ],
            options={
                'verbose_name': 'Choice Question',
                'verbose_name_plural': 'Choice Questions',
            },
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'verbose_name': 'Text Answer', 'verbose_name_plural': 'Text Answers'},
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100, verbose_name='choice text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.ChoiceQuestion')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
