# Generated by Django 2.2.7 on 2020-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200525_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('t', 'text'), ('d', 'dropdown'), ('r', 'radio'), ('c', 'checkbox')], default='d', help_text='select type of questionfor dropdown, radio, checkboxadd a the choice below', max_length=1, verbose_name='question type'),
            preserve_default=False,
        ),
    ]
