# Generated by Django 2.2.7 on 2020-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('position',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
