# Generated by Django 2.2.7 on 2020-05-24 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_multiplechoicequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={'verbose_name': 'Multiple Choice Question', 'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50)),
                ('question', models.ManyToManyField(to='questions.MultipleChoiceQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multiple Choice',
                'verbose_name_plural': 'Multiple Choices',
            },
        ),
    ]
